package com.andrerinas.openheadunit.utils

import java.io.File

/**
 * Reads an interface's MAC from outside the framework, for when
 * `NetworkInterface.getHardwareAddress()` returns null or a placeholder — the norm for ordinary
 * apps since Android 6.0.
 *
 * Separate from `WifiDirectManager.getMacFromShell()` on purpose: that one carries `[BUG_FIX]`
 * annotations and a six-deep chain tuned against specific hardware, and sharing it would risk the
 * WiFi Direct path to serve the hotspot one. ~30 duplicated lines, minus its leak — it never
 * destroys the `ip link` process or closes its streams, and this runs on a poll loop.
 */
object InterfaceMacReader {

    private val PLACEHOLDERS = setOf("00:00:00:00:00:00", "02:00:00:00:00:00")

    /** The MAC of [iface] from hostapd_cli, sysfs, or ip link, or null if none yields a real one. */
    fun read(iface: String): String? = fromHostapd(iface) ?: fromSysfs(iface) ?: fromIpLink(iface)

    /** Queries hostapd_cli for the exact live active BSSID generated by hostapd */
    fun fromHostapd(iface: String): String? {
        val cmds = listOf(
            arrayOf("hostapd_cli", "-i", iface, "status"),
            arrayOf("hostapd_cli", "-i", iface, "-p", "/data/misc/wifi/hostapd/ctrl", "status"),
            arrayOf("hostapd_cli", "-i", iface, "-p", "/data/vendor/wifi/hostapd/ctrl", "status"),
            arrayOf("/dev/hostapd_cli", "-i", iface, "status"),
            arrayOf("/system/bin/hostapd_cli", "-i", iface, "status")
        )
        for (cmd in cmds) {
            var process: Process? = null
            try {
                process = Runtime.getRuntime().exec(cmd)
                val output = process.inputStream.bufferedReader().use { it.readText() }
                val match = Regex("bssid=(([0-9a-fA-F]{2}:){5}[0-9a-fA-F]{2})", RegexOption.IGNORE_CASE).find(output)
                val found = usableOrNull(match?.groupValues?.get(1))
                if (found != null) {
                    AppLog.i("InterfaceMacReader: Retrieved live hostapd BSSID ($found) for $iface via ${cmd.joinToString(" ")}")
                    return found
                }
            } catch (_: Exception) {
            } finally {
                try { process?.errorStream?.close() } catch (_: Exception) {}
                try { process?.outputStream?.close() } catch (_: Exception) {}
                try { process?.destroy() } catch (_: Exception) {}
            }
        }
        return null
    }

    /** `/sys/class/net/<iface>/address`. Readable without root on most head units. */
    fun fromSysfs(iface: String): String? = try {
        val file = File("/sys/class/net/$iface/address")
        if (file.exists()) usableOrNull(file.readText()) else null
    } catch (e: Exception) {
        AppLog.d("InterfaceMacReader: sysfs read for $iface failed: ${e.message}")
        null
    }

    /** `ip link show <iface>`, parsed for its `link/ether` line. */
    fun fromIpLink(iface: String): String? {
        var process: Process? = null
        return try {
            process = Runtime.getRuntime().exec(arrayOf("ip", "link", "show", iface))
            val output = process.inputStream.bufferedReader().use { it.readText() }
            val match = Regex("link/ether (([0-9a-fA-F]{2}:){5}[0-9a-fA-F]{2})").find(output)
            usableOrNull(match?.groupValues?.get(1))
        } catch (e: Exception) {
            AppLog.d("InterfaceMacReader: 'ip link show $iface' failed: ${e.message}")
            null
        } finally {
            // An undestroyed Process keeps its file descriptors, and on some ROMs its zombie,
            // for the life of the app.
            try { process?.errorStream?.close() } catch (e: Exception) {}
            try { process?.outputStream?.close() } catch (e: Exception) {}
            try { process?.destroy() } catch (e: Exception) {}
        }
    }

    /** [mac] normalised to lower case, or null if it is blank or a masking placeholder. */
    private fun usableOrNull(mac: String?): String? {
        val trimmed = mac?.trim()?.lowercase().orEmpty()
        return if (trimmed.isEmpty() || trimmed in PLACEHOLDERS) null else trimmed
    }
}
